Repository GSG-CF04/openTriviaApi-Nabil-Ahmed, pull requests merged in 2021-11, with the labels that each got.

#2 initialize project files structure
  categories.html
  css/categories.css
  css/index.css
  css/quest.css
  index.html
  js/categories.js
  js/index.js
  js/quest.js
  quest.html
Labels: waiting review

#6 create categories page using html & css
  assets/imgs/back.svg
  categories.html
  css/categories.css
Labels: approved

#5 create index page using html & css
  assets/imgs/logo.svg
  css/index.css
  index.html
Labels: approved

#8 fetch questions categories using openTdb Api
  categories.html
  css/categories.css
  js/categories.js
Labels: approved

#12 set user name to the local storage
  index.html
  js/index.js
Labels: waiting review

#10 set category id to the localstorage
  js/categories.js
Labels: waiting review

#15 Quest interface html/css added
  css/quest.css
  quest.html
Labels: awaiting review

#18 fix navigation to questions page
  js/categories.js
Labels: approved

#20 final product adding
  css/quest.css
  js/quest.js
  quest.html
Labels: approved

#22 create submit sunction and show score
  js/quest.js
  quest.html
Labels: awaiting review

#24 adding readme file
  README.md
Labels: approved
